### ISSUE TITLE
"Create Object Initializer" Code Refactoring should not be suggested for collection types

### ISSUE THREAD

**Issue by KerbalSpike** [Flash0ver/F0.Analyzers#53]
![image](https://user-images.githubusercontent.com/18031240/102939391-7e5db200-44ae-11eb-8c05-493b6d28232d.png)

Code to reproduce:

```
using System.Collections.Generic;

namespace Test
{
	class Class1
	{
		public void Test()
		{
			var x = new List<string>();
		}
	}
}
```

**Comment by Flash0ver** [comment]
Fixed in *v0.6.1* - the "Create Object Initializer" Code Refactoring no longer registers a code action with collection types.
Thank you @KerbalSpike for trying out our Analyzers and reporting this issue.
